# Generated by Django 5.0.1 on 2024-03-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customeruser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='address',
            field=models.CharField(max_length=500),
        ),
    ]
