# Generated by Django 5.0.1 on 2024-02-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_product_order_product'),
        ('product', '0003_product_created_at_product_is_active_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', to='product.product'),
        ),
    ]
